In [46]:
import os
import sys
import logging
from google.cloud import bigquery
from typing import List
from google.cloud import bigquery
from google.oauth2 import service_account
import pyarrow
import pandas as pd

In [47]:
#transform historical data set to better fit the scraped data
historical_df_3_cities = pd.read_csv('./data/3 cities weather.csv')
historical_df_austine_stpaul_barrow = pd.read_csv('./data/Austin_StPaul_Barrow.csv')
historical_df_cordova = pd.read_csv('./data/cordova, AK 2022-02-21 to 2023-02-21.csv')
historical_df_international = pd.read_csv('./data/international_cities.csv')
res = [historical_df_austine_stpaul_barrow, historical_df_3_cities, historical_df_cordova, historical_df_international]
historical_df = pd.concat(res)
historical_df = historical_df.rename({'feelslikemin': 'windchill', 'dew': 'dewpoint'}, axis=1)
historical_df['datetime'] = pd.to_datetime(historical_df['datetime'])
historical_df = historical_df.drop(['icon','sunrise','sunset','precipcover','solarenergy','solarradiation'], axis=1)
display(historical_df.head(3))

,name,datetime,tempmax,tempmin,temp,feelslikemax,windchill,feelslike,dewpoint,humidity,...,winddir,sealevelpressure,cloudcover,visibility,uvindex,severerisk,moonphase,conditions,description,stations
0,St. Paul,2022-02-21,26.1,16.1,21.7,15.8,2.1,9.5,12.0,65.8,...,51.3,1017.8,96.0,9.9,1,10.0,0.68,Overcast,Cloudy skies throughout the day.,"C5560,KSTP,KSGS,72658414927,72660304974,KMSP,7..."
1,St. Paul,2022-02-22,15.2,5.0,9.0,1.9,-12.5,-8.0,2.6,75.0,...,351.9,1021.8,96.3,3.8,2,10.0,0.72,"Snow, Overcast",Cloudy skies throughout the day with snow in t...,"C5560,KSTP,KSGS,72658414927,72660304974,KMSP,7..."
2,St. Paul,2022-02-23,11.8,-2.1,3.6,5.6,-20.2,-10.4,-8.2,58.4,...,319.3,1037.8,1.4,9.9,6,10.0,0.75,Clear,Clear conditions throughout the day.,"C5560,KSTP,KSGS,72658414927,72660304974,KMSP,7..."

In [48]:
#authorization
key_path = "/home/reed/.creds/weather_team_week.json"
credentials = service_account.Credentials.from_service_account_file(
    key_path, scopes=["https://www.googleapis.com/auth/cloud-platform"])

client = bigquery.Client(credentials=credentials, project=credentials.project_id,)

In [49]:
# **** SETUP LOGGING ****
# setup logging and logger
logging.basicConfig(            # setting up the root logger
    format='[%(levelname)-5s][%(asctime)s][%(module)s:%(lineno)04d] : %(message)s',
    level=logging.INFO,
    stream=sys.stdout
)
logger: logging.Logger = logging.getLogger('root')      # alias the root logger as `logger`
logger.setLevel(logging.DEBUG)                          # programmatically reassign the logging level

In [50]:
# change to match your filesystem
PROJECT_NAME = credentials.project_id
DATASET_NAME = "reed_weather_data"

# **** BIGQUERY DATASET CREATION ****

dataset_id = f"{PROJECT_NAME}.{DATASET_NAME}"
dataset = bigquery.Dataset(dataset_id)
dataset.location = "US"
dataset = client.create_dataset(dataset, exists_ok=True)

logger.info(f"Created emissions dataset: {dataset.full_dataset_id}")

FACTS_TABLE_METADATA = {
    'weather_data': {
        'table_name': 'weather_data',
        'schema': [
            # indexes are written if only named in the schema
            bigquery.SchemaField('name', 'STRING', mode='REQUIRED'),
            bigquery.SchemaField('datetime', 'DATETIME', mode='NULLABLE'),
            bigquery.SchemaField('tempmax', 'FLOAT64', mode='NULLABLE'),
            bigquery.SchemaField('tempmin', 'FLOAT64', mode='NULLABLE'),
            bigquery.SchemaField('temp', 'FLOAT64', mode='NULLABLE'),
            bigquery.SchemaField('feelslikemax', 'FLOAT64', mode='NULLABLE'),
            bigquery.SchemaField('windchill', 'FLOAT64', mode='NULLABLE'),
            bigquery.SchemaField('feelslike', 'FLOAT64', mode='NULLABLE'),
            bigquery.SchemaField('dewpoint', 'FLOAT64', mode='NULLABLE'),
            bigquery.SchemaField('humidity', 'FLOAT64', mode='NULLABLE'),
            bigquery.SchemaField('precip', 'FLOAT64', mode='NULLABLE'),
            bigquery.SchemaField('precipprob', 'FLOAT64', mode='NULLABLE'),
            bigquery.SchemaField('preciptype', 'STRING', mode='NULLABLE'),
            bigquery.SchemaField('snow', 'FLOAT64', mode='NULLABLE'),
            bigquery.SchemaField('snowdepth', 'FLOAT64', mode='NULLABLE'),
            bigquery.SchemaField('windgust', 'FLOAT64', mode='NULLABLE'),
            bigquery.SchemaField('windspeed', 'FLOAT64', mode='NULLABLE'),
            bigquery.SchemaField('winddir', 'FLOAT64', mode='NULLABLE'),
            bigquery.SchemaField('sealevelpressure', 'FLOAT64', mode='NULLABLE'),
            bigquery.SchemaField('cloudcover', 'FLOAT64', mode='NULLABLE'),
            bigquery.SchemaField('visibility', 'FLOAT64', mode='NULLABLE'),
            bigquery.SchemaField('uvindex', 'INT64', mode='NULLABLE'),
            bigquery.SchemaField('severerisk', 'FLOAT64', mode='NULLABLE'),
            bigquery.SchemaField('moonphase', 'FLOAT64', mode='NULLABLE'),
            bigquery.SchemaField('conditions', 'STRING', mode='NULLABLE'),
            bigquery.SchemaField('description', 'STRING', mode='NULLABLE'),
            bigquery.SchemaField('stations', 'STRING', mode='NULLABLE'),
        ]
    }      
}

[INFO ][2023-02-21 16:58:31,899][1575352606:0012] : Created emissions dataset: team-week3:reed_weather_data

In [51]:
def load_table(
    df: pd.DataFrame, 
    client: bigquery.Client, 
    table_name: str, 
    schema: List[bigquery.SchemaField], 
    create_disposition: str = 'CREATE_IF_NEEDED', 
    write_disposition: str = 'WRITE_TRUNCATE'
    ) -> None:
    """load dataframe into bigquery table

    Args:
        df (pd.DataFrame): dataframe to load
        client (bigquery.Client): bigquery client
        table_name (str): full table name including project and dataset id
        schema (List[bigquery.SchemaField]): table schema with data types
        create_disposition (str, optional): create table disposition. Defaults to 'CREATE_IF_NEEDED'.
        write_disposition (str, optional): overwrite table disposition. Defaults to 'WRITE_TRUNCATE'.
    """
    # *** run some checks ***
    # test table name to be full table name including project and dataset name. It must contain to dots
    assert len(table_name.split('.')) == 3, f"Table name must be a full bigquery table name including project and dataset id: '{table_name}'"
    # setup bigquery load job:
    #  create table if needed, replace rows, define the table schema
    job_config = bigquery.LoadJobConfig(
        create_disposition=create_disposition,
        write_disposition=write_disposition,
        schema=schema
    )
    logger.info(f"loading table: '{table_name}'")
    job = client.load_table_from_dataframe(df, destination=table_name, job_config=job_config)
    job.result()        # wait for the job to finish
    # get the resulting table
    table = client.get_table(table_name)
    logger.info(f"loaded {table.num_rows} rows into {table.full_table_id}")

In [52]:
# Load weather_data dimension table

# get table name and schema from FACTS_TABLE_METADATA config param
table_name = f"{PROJECT_NAME}.{DATASET_NAME}.{FACTS_TABLE_METADATA['weather_data']['table_name']}"
schema = FACTS_TABLE_METADATA['weather_data']['schema']
# load dataframe
load_table(historical_df, client, table_name, schema)

logger.info(f"loaded weather_data")

[INFO ][2023-02-21 16:58:32,020][1947479415:0029] : loading table: 'team-week3.reed_weather_data.weather_data'
[INFO ][2023-02-21 16:58:38,298][1947479415:0034] : loaded 14682 rows into team-week3:reed_weather_data.weather_data
[INFO ][2023-02-21 16:58:38,298][4025926169:0009] : loaded weather_data

In [53]:
historical_df['preciptype'].unique()

array(['snow', nan, 'rain,snow', 'rain,freezingrain,snow',
       'freezingrain,snow', 'freezingrain', 'rain', 'rain,ice',
       'rain,freezingrain,snow,ice', 'rain,freezingrain', 'snow,ice',
       'ice', 'freezingrain,snow,ice', 'rain,freezingrain,ice',
       'rain,snow,ice'], dtype=object)